name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        . venv/bin/activate
        flake8 .

    - name: Test with pytest
      run: |
        . venv/bin/activate
        pytest

    - name: Security analysis with Bandit
      run: |
        . venv/bin/activate
        bandit -r app

    - name: Security analysis with Safety
      run: |
        . venv/bin/activate
        safety check
